"""Versioned, owner-scoped knowledge export and import helpers."""

import io
import json
import re
import zipfile
from collections import Counter
from pathlib import Path

from django.core.exceptions import ValidationError
from django.db import transaction
from django.utils import timezone
from django.utils.dateparse import parse_datetime
from django.utils.text import slugify

from apps.reviews.models import ConceptReviewState, ReviewLog

from .models import Category, CodeSnippet, CommonMistake, Concept, ConceptAlias, ConceptRelation, Tag, normalized


EXPORT_FORMAT = "mindrepo"
EXPORT_VERSION = 1
MAX_IMPORT_BYTES = 2 * 1024 * 1024
MAX_IMPORT_CONCEPTS = 2_000


def _date(value):
    return value.isoformat() if value else None


def _concepts(user):
    return Concept.objects.filter(owner=user).select_related("category", "review_state").prefetch_related(
        "tags", "aliases", "snippets", "mistakes", "attachments", "outgoing_relations__target", "review_logs"
    )


def build_export(user, *, include_reviews=True):
    concepts = list(_concepts(user))
    data = {"categories": [], "concepts": []}
    for category in Category.objects.filter(owner=user).select_related("parent"):
        data["categories"].append({"id": str(category.pk), "title": category.title, "description": category.description, "parent_id": str(category.parent_id) if category.parent_id else None})
    for concept in concepts:
        row = {"id": str(concept.pk), "title": concept.title, "slug": concept.slug, "quick_definition": concept.quick_definition, "simple_explanation": concept.simple_explanation, "deep_dive": concept.deep_dive, "difficulty": concept.difficulty, "is_favorite": concept.is_favorite, "category_id": str(concept.category_id) if concept.category_id else None, "tags": [tag.name for tag in concept.tags.all()], "aliases": [item.value for item in concept.aliases.all()], "snippets": [{"title": item.title, "language": item.language, "code": item.code, "explanation": item.explanation, "sort_order": item.sort_order} for item in concept.snippets.all()], "mistakes": [{"title": item.title, "description": item.description, "correction": item.correction, "sort_order": item.sort_order} for item in concept.mistakes.all()], "attachments": [{"name": item.original_name, "content_type": item.content_type, "file_size": item.file_size} for item in concept.attachments.all()], "relations": [{"target_id": str(item.target_id), "relation_type": item.relation_type} for item in concept.outgoing_relations.all()], "created_at": _date(concept.created_at), "updated_at": _date(concept.updated_at)}
        if include_reviews:
            state = concept.review_state
            row["review_state"] = {"status": state.status, "due_at": _date(state.due_at), "last_reviewed_at": _date(state.last_reviewed_at), "review_count": state.review_count, "lapse_count": state.lapse_count, "success_streak": state.success_streak, "interval_days": state.interval_days, "version": state.version, "scheduler_data": state.scheduler_data}
            row["review_logs"] = [{"rating": log.rating, "reviewed_at": _date(log.reviewed_at), "previous_status": log.previous_status, "new_status": log.new_status, "previous_due_at": _date(log.previous_due_at), "new_due_at": _date(log.new_due_at), "previous_interval_days": log.previous_interval_days, "new_interval_days": log.new_interval_days, "scheduler_version": log.scheduler_version} for log in concept.review_logs.all()]
        data["concepts"].append(row)
    return {"format": EXPORT_FORMAT, "version": EXPORT_VERSION, "exported_at": timezone.now().isoformat(), "data": data}


def export_json(user, include_reviews=True):
    return json.dumps(build_export(user, include_reviews=include_reviews), ensure_ascii=False, indent=2)


def safe_filename(value, fallback="concept"):
    value = slugify(value, allow_unicode=True) or fallback
    return re.sub(r'[<>:"/\\|?*]+', "-", value).strip(". ")[:100] or fallback


def safe_attachment_filename(value):
    suffix = Path(value).suffix.lower()
    return f"{safe_filename(Path(value).stem, 'attachment')}{suffix}"


def export_markdown_zip(user):
    concepts = list(_concepts(user))
    payload = build_export(user, include_reviews=False)
    concept_attachments = {str(concept.pk): list(concept.attachments.all()) for concept in concepts}
    used = Counter()
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("MindRepo/README.md", "# MindRepo export\n\nPortable Markdown export generated by MindRepo.\n")
        categories = {item["id"]: item["title"] for item in payload["data"]["categories"]}
        concept_titles = {item["id"]: item["title"] for item in payload["data"]["concepts"]}
        for concept in payload["data"]["concepts"]:
            folder = safe_filename(categories.get(concept["category_id"], "Uncategorized"), "Uncategorized")
            base = safe_filename(concept["title"])
            used[(folder, base)] += 1
            suffix = "" if used[(folder, base)] == 1 else f"-{used[(folder, base)]}"
            lines = [f"# {concept['title']}", "", f"Category: {categories.get(concept['category_id'], 'Uncategorized')}", f"Difficulty: {concept['difficulty'].title()}", f"Tags: {', '.join(concept['tags'])}", "", "## Quick Recall", "", concept["quick_definition"], ""]
            for title, content in (("Simple Explanation", concept["simple_explanation"]), ("Deep Dive", concept["deep_dive"])):
                if content:
                    lines.extend([f"## {title}", "", content, ""])
            if concept["aliases"]:
                lines.extend(["## Aliases", "", *[f"- {item}" for item in concept["aliases"]], ""])
            for snippet in concept["snippets"]:
                lines.extend([f"## Code Example: {snippet['title'] or snippet['language']}", "", f"```{snippet['language']}", snippet["code"], "```", ""])
                if snippet["explanation"]:
                    lines.extend([snippet["explanation"], ""])
            if concept["mistakes"]:
                lines.extend(["## Common Mistakes", ""])
                for mistake in concept["mistakes"]:
                    lines.extend([f"### {mistake['title']}", "", mistake["description"], ""])
                    if mistake["correction"]:
                        lines.extend([f"Better approach: {mistake['correction']}", ""])
            if concept["relations"]:
                lines.extend(["## Related Concepts", ""])
                lines.extend([f"- {concept_titles.get(item['target_id'], item['target_id'])} ({item['relation_type']})" for item in concept["relations"]])
                lines.append("")
            attachments = concept_attachments.get(concept["id"], [])
            if attachments:
                attachment_dir = f"{base}{suffix}-attachments"
                lines.extend(["## Attachments", ""])
                attachment_names = Counter()
                for attachment in attachments:
                    attachment_name = safe_attachment_filename(attachment.original_name)
                    attachment_names[attachment_name] += 1
                    if attachment_names[attachment_name] > 1:
                        stem, dot, extension = attachment_name.rpartition(".")
                        attachment_name = f"{stem or attachment_name}-{attachment_names[attachment_name]}{dot}{extension}" if dot else f"{attachment_name}-{attachment_names[attachment_name]}"
                    lines.append(f"- [{attachment.original_name}]({attachment_dir}/{attachment_name})")
                    attachment.file.open("rb")
                    try:
                        archive.writestr(f"MindRepo/{folder}/{attachment_dir}/{attachment_name}", attachment.file.read())
                    finally:
                        attachment.file.close()
                lines.append("")
            archive.writestr(f"MindRepo/{folder}/{base}{suffix}.md", "\n".join(lines))
    return buffer.getvalue()


def validate_import(payload, user):
    if not isinstance(payload, dict) or payload.get("format") != EXPORT_FORMAT:
        raise ValidationError("This is not a MindRepo export file.")
    if payload.get("version") != EXPORT_VERSION:
        raise ValidationError("This export format version is not supported.")
    data = payload.get("data")
    if not isinstance(data, dict) or not isinstance(data.get("categories", []), list) or not isinstance(data.get("concepts", []), list):
        raise ValidationError("The export data is incomplete.")
    categories, concepts = data["categories"], data["concepts"]
    if len(concepts) > MAX_IMPORT_CONCEPTS:
        raise ValidationError("This import contains too many concepts.")
    errors = []
    category_ids = set()
    for item in categories:
        if not isinstance(item, dict) or not item.get("id") or not str(item.get("title", "")).strip():
            errors.append("Every category needs an id and title.")
        else:
            if str(item["id"]) in category_ids:
                errors.append("Category export identifiers must be unique.")
            category_ids.add(str(item["id"]))
    for item in categories:
        if isinstance(item, dict) and item.get("parent_id") and str(item["parent_id"]) not in category_ids:
            errors.append("A category refers to an unknown parent.")
    concept_ids = set()
    for item in concepts:
        if not isinstance(item, dict) or not item.get("id") or not str(item.get("title", "")).strip() or not str(item.get("quick_definition", "")).strip():
            errors.append("Every concept needs an id, title, and quick definition.")
            continue
        if str(item["id"]) in concept_ids:
            errors.append("Concept export identifiers must be unique.")
        if item.get("difficulty") not in Concept.Difficulty.values:
            errors.append(f"Invalid difficulty for {item['title']}.")
        if item.get("category_id") and str(item["category_id"]) not in category_ids:
            errors.append(f"Unknown category for {item['title']}.")
        concept_ids.add(str(item["id"]))
        for field in ("tags", "aliases", "snippets", "mistakes", "relations", "review_logs"):
            if field in item and not isinstance(item[field], list):
                errors.append(f"Invalid {field} collection in {item['title']}.")
        alias_values = [normalized(str(value)) for value in item.get("aliases", []) if str(value).strip()]
        if len(alias_values) != len(set(alias_values)):
            errors.append(f"Duplicate aliases in {item['title']}.")
        for snippet in item.get("snippets", []):
            if not isinstance(snippet, dict) or not snippet.get("code") or not re.fullmatch(r"[a-z0-9+.#_-]+", str(snippet.get("language", "plaintext")).lower()):
                errors.append(f"Invalid code snippet in {item['title']}.")
        for mistake in item.get("mistakes", []):
            if not isinstance(mistake, dict) or not mistake.get("title") or not mistake.get("description"):
                errors.append(f"Invalid common mistake in {item['title']}.")
        for log in item.get("review_logs", []):
            required_log_fields = {"rating", "reviewed_at", "previous_status", "new_status", "previous_due_at", "new_due_at", "previous_interval_days", "new_interval_days"}
            if not isinstance(log, dict) or not required_log_fields.issubset(log) or log.get("rating") not in ReviewLog.Rating.values:
                errors.append(f"Invalid review log in {item['title']}.")
                continue
            dates = [parse_datetime(str(log.get(key, ""))) for key in ("reviewed_at", "previous_due_at", "new_due_at")]
            if not all(date and timezone.is_aware(date) for date in dates):
                errors.append(f"Invalid review timestamp in {item['title']}.")
        if item.get("review_state") and not isinstance(item["review_state"], dict):
            errors.append(f"Invalid review state in {item['title']}.")
        elif item.get("review_state") and item["review_state"].get("status") not in ConceptReviewState.Status.values:
            errors.append(f"Invalid review state in {item['title']}.")
        if isinstance(item.get("review_state"), dict) and item["review_state"].get("due_at"):
            due_at = parse_datetime(str(item["review_state"]["due_at"]))
            if not due_at or not timezone.is_aware(due_at):
                errors.append(f"Invalid review state timestamp in {item['title']}.")
    for item in concepts:
        for relation in item.get("relations", []):
            if not isinstance(relation, dict) or str(relation.get("target_id")) not in concept_ids or relation.get("relation_type") not in ConceptRelation.Type.values:
                errors.append(f"Invalid relation in {item.get('title', 'concept')}.")
    parents = {str(item["id"]): str(item["parent_id"]) for item in categories if isinstance(item, dict) and item.get("parent_id")}
    for item_id in parents:
        seen, current = set(), item_id
        while current in parents:
            if current in seen:
                errors.append("Category hierarchy contains a cycle.")
                break
            seen.add(current)
            current = parents[current]
    if errors:
        raise ValidationError(sorted(set(errors)))
    existing = {normalized(title) for title in Concept.objects.filter(owner=user).values_list("title", flat=True)}
    duplicates = [item["title"] for item in concepts if normalized(item["title"]) in existing]
    return {"categories": len(categories), "concepts": len(concepts), "relations": sum(len(item.get("relations", [])) for item in concepts), "review_logs": sum(len(item.get("review_logs", [])) for item in concepts), "duplicates": duplicates}


def _copy_title(user, title):
    candidate, number = f"{title} (imported)", 2
    while Concept.objects.filter(owner=user, title=candidate).exists():
        candidate = f"{title} (imported {number})"
        number += 1
    return candidate


def apply_import(user, payload, strategy="skip"):
    validate_import(payload, user)
    if strategy not in {"skip", "copy"}:
        raise ValidationError("Invalid duplicate strategy.")
    data, result = payload["data"], {"categories": 0, "concepts": 0, "skipped": 0, "relations": 0, "review_logs": 0}
    with transaction.atomic():
        category_map, pending = {}, list(data["categories"])
        while pending:
            before = len(pending)
            for item in pending[:]:
                parent = category_map.get(str(item.get("parent_id"))) if item.get("parent_id") else None
                if item.get("parent_id") and not parent:
                    continue
                category, created = Category.objects.get_or_create(owner=user, parent=parent, title=item["title"], defaults={"description": item.get("description", "")})
                category_map[str(item["id"])] = category
                result["categories"] += int(created)
                pending.remove(item)
            if len(pending) == before:
                raise ValidationError("Could not build the category hierarchy.")
        concept_map, created_ids = {}, set()
        existing_by_title = {normalized(item.title): item for item in Concept.objects.filter(owner=user)}
        for item in data["concepts"]:
            duplicate = existing_by_title.get(normalized(item["title"]))
            if duplicate and strategy == "skip":
                concept_map[str(item["id"])] = duplicate
                result["skipped"] += 1
                continue
            title = _copy_title(user, item["title"]) if duplicate else item["title"]
            concept = Concept.objects.create(owner=user, title=title, quick_definition=item["quick_definition"], simple_explanation=item.get("simple_explanation", ""), deep_dive=item.get("deep_dive", ""), difficulty=item["difficulty"], is_favorite=bool(item.get("is_favorite")), category=category_map.get(str(item.get("category_id"))))
            concept_map[str(item["id"])] = concept
            created_ids.add(str(item["id"]))
            existing_by_title[normalized(title)] = concept
            result["concepts"] += 1
            tags = []
            for name in item.get("tags", []):
                name = str(name).strip()
                if name:
                    tag, _ = Tag.objects.get_or_create(owner=user, normalized_name=normalized(name), defaults={"name": name})
                    tags.append(tag)
            concept.tags.set(tags)
            ConceptAlias.objects.bulk_create([ConceptAlias(concept=concept, value=str(value).strip(), normalized_value=normalized(str(value))) for value in item.get("aliases", []) if str(value).strip()])
            CodeSnippet.objects.bulk_create([CodeSnippet(concept=concept, title=row.get("title", ""), language=row.get("language", "plaintext"), code=row.get("code", ""), explanation=row.get("explanation", ""), sort_order=row.get("sort_order", 0)) for row in item.get("snippets", []) if row.get("code")])
            CommonMistake.objects.bulk_create([CommonMistake(concept=concept, title=row.get("title", ""), description=row.get("description", ""), correction=row.get("correction", ""), sort_order=row.get("sort_order", 0)) for row in item.get("mistakes", []) if row.get("title") and row.get("description")])
        for item in data["concepts"]:
            if str(item["id"]) not in created_ids:
                continue
            source = concept_map[str(item["id"])]
            for relation in item.get("relations", []):
                target = concept_map[str(relation["target_id"])]
                if source != target:
                    _, created = ConceptRelation.objects.get_or_create(source=source, target=target, relation_type=relation["relation_type"])
                    result["relations"] += int(created)
        for item in data["concepts"]:
            if str(item["id"]) not in created_ids:
                continue
            concept, state_data = concept_map[str(item["id"])], item.get("review_state")
            if state_data:
                ConceptReviewState.objects.filter(concept=concept).update(**{key: state_data[key] for key in ("status", "review_count", "lapse_count", "success_streak", "interval_days", "version", "scheduler_data") if key in state_data}, due_at=parse_datetime(state_data["due_at"]) if state_data.get("due_at") else timezone.now(), last_reviewed_at=parse_datetime(state_data["last_reviewed_at"]) if state_data.get("last_reviewed_at") else None)
                ReviewLog.objects.bulk_create([ReviewLog(concept=concept, rating=row["rating"], reviewed_at=parse_datetime(row["reviewed_at"]), previous_status=row["previous_status"], new_status=row["new_status"], previous_due_at=parse_datetime(row["previous_due_at"]), new_due_at=parse_datetime(row["new_due_at"]), previous_interval_days=row["previous_interval_days"], new_interval_days=row["new_interval_days"], scheduler_version=row.get("scheduler_version", "mindrepo-v1")) for row in item.get("review_logs", [])])
                result["review_logs"] += len(item.get("review_logs", []))
    return result
