# Generated by Django 5.2.17 on 2026-09-07 10:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, max_length=180)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='knowledge.category')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, max_length=180)),
                ('title', models.CharField(max_length=180)),
                ('quick_definition', models.TextField()),
                ('simple_explanation', models.TextField(blank=True)),
                ('deep_dive', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concepts', to='knowledge.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CommonMistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('correction', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='knowledge.concept')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('language', models.CharField(default='plaintext', max_length=32, validators=[django.core.validators.RegexValidator('^[a-z0-9+.#_-]+$')])),
                ('code', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='knowledge.concept')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ConceptAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=180)),
                ('normalized_value', models.CharField(max_length=180)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='knowledge.concept')),
            ],
            options={
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='ConceptRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('related', 'Related'), ('prerequisite', 'Prerequisite'), ('extends', 'Extends'), ('contrasts', 'Contrasts'), ('example_of', 'Example of')], default='related', max_length=20)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='knowledge.concept')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='knowledge.concept')),
            ],
            options={
                'ordering': ['target__title'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('normalized_name', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='concept',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='concepts', to='knowledge.tag'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='knowledge_category_owner_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('owner', 'title'), name='knowledge_root_category_title_unique'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('owner', 'parent', 'title'), name='knowledge_child_category_title_unique'),
        ),
        migrations.AddIndex(
            model_name='conceptalias',
            index=models.Index(fields=['normalized_value'], name='knowledge_c_normali_3d1531_idx'),
        ),
        migrations.AddConstraint(
            model_name='conceptalias',
            constraint=models.UniqueConstraint(fields=('concept', 'normalized_value'), name='knowledge_alias_unique'),
        ),
        migrations.AddConstraint(
            model_name='conceptrelation',
            constraint=models.UniqueConstraint(fields=('source', 'target', 'relation_type'), name='knowledge_relation_unique'),
        ),
        migrations.AddConstraint(
            model_name='conceptrelation',
            constraint=models.CheckConstraint(condition=models.Q(('source', models.F('target')), _negated=True), name='knowledge_relation_not_self'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['owner', 'normalized_name'], name='knowledge_t_owner_i_4d9ffb_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('owner', 'normalized_name'), name='knowledge_tag_unique'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['owner', '-updated_at'], name='knowledge_c_owner_i_e8cae8_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['owner', 'difficulty'], name='knowledge_c_owner_i_3f9532_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['owner', 'is_favorite'], name='knowledge_c_owner_i_41782f_idx'),
        ),
        migrations.AddConstraint(
            model_name='concept',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='knowledge_concept_owner_slug_unique'),
        ),
    ]
