# Generated by Django 5.2.17 on 2026-09-08 08:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['owner', 'title'], name='knowledge_c_owner_i_decd4d_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['owner', 'title'], name='knowledge_c_owner_i_509b8b_idx'),
        ),
    ]
