# Generated by Django 5.2.17 on 2026-09-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_category_knowledge_c_owner_i_decd4d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='sync_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
