# Generated by Django 5.2.17 on 2026-09-08 21:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_conceptattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='freshness_status',
            field=models.CharField(choices=[('current', 'Current'), ('needs_verification', 'Needs verification'), ('outdated', 'Outdated')], default='needs_verification', max_length=24),
        ),
        migrations.AddField(
            model_name='concept',
            name='last_verified_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concept',
            name='verification_note',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ConceptContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(max_length=120)),
                ('version', models.CharField(blank=True, max_length=80)),
                ('note', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='knowledge.concept')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ConceptSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('section_type', models.CharField(choices=[('standard', 'Standard section'), ('key_takeaways', 'Key takeaways'), ('note', 'Important note'), ('warning', 'Warning / gotcha'), ('best_practices', 'Best practices'), ('comparison', 'Comparison'), ('diagram', 'Diagram')], default='standard', max_length=24)),
                ('content', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='knowledge.concept')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ConceptSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('documentation', 'Documentation'), ('book', 'Book'), ('article', 'Article'), ('course', 'Course'), ('video', 'Video'), ('paper', 'Paper'), ('repository', 'Repository'), ('company_documentation', 'Company documentation'), ('personal_experience', 'Personal experience'), ('other', 'Other')], default='documentation', max_length=32)),
                ('url', models.URLField(blank=True)),
                ('author', models.CharField(blank=True, max_length=160)),
                ('publisher', models.CharField(blank=True, max_length=160)),
                ('version', models.CharField(blank=True, max_length=80)),
                ('note', models.TextField(blank=True)),
                ('accessed_at', models.DateField(blank=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='knowledge.concept')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ConceptRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('source', models.CharField(choices=[('create', 'Create'), ('edit', 'Edit'), ('import', 'Import'), ('restore', 'Restore')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='knowledge.concept')),
            ],
            options={
                'ordering': ['-revision_number'],
                'constraints': [models.UniqueConstraint(fields=('concept', 'revision_number'), name='knowledge_revision_number_unique')],
            },
        ),
    ]
