# Generated by Django 5.2.17 on 2026-09-08 07:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def create_review_states(apps, schema_editor):
    Concept = apps.get_model("knowledge", "Concept")
    ConceptReviewState = apps.get_model("reviews", "ConceptReviewState")
    now = django.utils.timezone.now()
    ConceptReviewState.objects.bulk_create(
        [ConceptReviewState(concept_id=concept_id, due_at=now) for concept_id in Concept.objects.values_list("pk", flat=True)],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptReviewState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('review', 'Review'), ('relearning', 'Relearning')], default='new', max_length=16)),
                ('due_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('lapse_count', models.PositiveIntegerField(default=0)),
                ('success_streak', models.PositiveIntegerField(default=0)),
                ('interval_days', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=0)),
                ('scheduler_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_state', to='knowledge.concept')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'due_at'], name='reviews_con_status_ef30dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('again', 'Again'), ('hard', 'Hard'), ('good', 'Good'), ('easy', 'Easy')], max_length=8)),
                ('reviewed_at', models.DateTimeField()),
                ('previous_status', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('review', 'Review'), ('relearning', 'Relearning')], max_length=16)),
                ('new_status', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('review', 'Review'), ('relearning', 'Relearning')], max_length=16)),
                ('previous_due_at', models.DateTimeField()),
                ('new_due_at', models.DateTimeField()),
                ('previous_interval_days', models.PositiveIntegerField()),
                ('new_interval_days', models.PositiveIntegerField()),
                ('scheduler_version', models.CharField(default='mindrepo-v1', max_length=32)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='knowledge.concept')),
            ],
            options={
                'ordering': ['-reviewed_at', '-pk'],
                'indexes': [models.Index(fields=['concept', '-reviewed_at'], name='reviews_rev_concept_d8f5cc_idx'), models.Index(fields=['rating', '-reviewed_at'], name='reviews_rev_rating_f1e950_idx')],
            },
        ),
        migrations.RunPython(create_review_states, migrations.RunPython.noop),
    ]
