# Generated by Django 5.2.17 on 2026-09-08 21:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_concept_freshness_status_concept_last_verified_at_and_more'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('card_type', models.CharField(choices=[('concept_recall', 'Concept recall'), ('basic', 'Basic')], default='basic', max_length=20)),
                ('question', models.TextField(blank=True)),
                ('answer', models.TextField(blank=True)),
                ('hint', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_cards', to='knowledge.concept')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='reviewlog',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='reviews.reviewcard'),
        ),
        migrations.CreateModel(
            name='ReviewCardState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('review', 'Review'), ('relearning', 'Relearning')], default='new', max_length=16)),
                ('due_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('lapse_count', models.PositiveIntegerField(default=0)),
                ('success_streak', models.PositiveIntegerField(default=0)),
                ('interval_days', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=0)),
                ('scheduler_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='reviews.reviewcard')),
            ],
        ),
        migrations.AddConstraint(
            model_name='reviewcard',
            constraint=models.UniqueConstraint(condition=models.Q(('card_type', 'concept_recall')), fields=('concept', 'card_type'), name='reviews_one_default_card_per_concept'),
        ),
        migrations.AddIndex(
            model_name='reviewcardstate',
            index=models.Index(fields=['status', 'due_at'], name='reviews_rev_status_94075b_idx'),
        ),
    ]
